### ISSUE TITLE
Registering invalid credentials (sync action) ends without proper error message.

### ISSUE THREAD

**Issue by ujovlado** [keboola/looker-writer#6]
Bolo by super, keby mi to zahlasilo, co sa nepodarilo. Teraz to dava 400ku, s nejakou genericou message.

![Screenshot_2019-10-29_22-36-01](https://user-images.githubusercontent.com/419849/67811206-90a3b200-fa9c-11e9-8bc8-09d6233dacf5.png)
![Screenshot_2019-10-29_22-35-53](https://user-images.githubusercontent.com/419849/67811208-90a3b200-fa9c-11e9-9422-94d870c3876c.png)

**Comment by tomasfejfar** [comment]
Mrknu na to.

**Comment by tomasfejfar** [comment]
Už to posílá (s dev verzí z toho zalinkovaného PR) správně.

![image](https://user-images.githubusercontent.com/642928/68025967-8a851f80-fcae-11e9-8093-5e82a77b43c1.png)
