### ISSUE TITLE
Allow passing of Looker database connection name in register sync action

### ISSUE THREAD

**Issue by tomasfejfar** [keboola/looker-writer#7]
When we changed the registration from run to sync action, there was one significant change. The KBC_CONFIGID now holds random hash created for configData. Therefore - the database name in Looker is different each time the connection is registered. 

So we need UI to pass either the configuration ID or even the actual name? 

- [ ] UI: Pass name or configuration id from UI
- [ ] Backend: Allow name/configuration id in registration call's ConfigDefinition

**Comment by ujovlado** [comment]
@tomasfejfar nestacilo by vysrat sa na sync akciu, tie credentials tam len ulozit a cele si to poriesis v ramci "run" akcie?

Pripadne, ak by si prichystal "testLookerCredentails" sync akciu, mozem to nechat ako je to teraz, akurat bude istota, ze si ukladam overene credentials.

**Comment by ujovlado** [comment]
> UI: Pass name or configuration id from UI

Toto samozrejme tiez nie je problem spravit. Staci ked mi povies, kde v `parameters` to chces a pridam to tam.

**Comment by tomasfejfar** [comment]
Chtělo by to aby byly validované IMHO. Tak já připravím testLookerCredentails sync akci. Ta registrace asi dává smysl v RUN (pokud nebude). Teď jdu s Timem ven a pak na to mrknu.

**Comment by ujovlado** [comment]
Ok, porozmyslaj, ani jedna z variant nie je pre nas problem, kedze tu sync akciu uz mame ready.

**Comment by tomasfejfar** [comment]
Fixed by different architecture.
